/**
 * Comprehensive registry of all user profile fields.
 *
 * IMPORTANT: This registry MUST be updated when new fields are added to UserProfile types.
 * The relationship arrays (usedByRiskFactors, usedByDiseases, mappedFromQuestions)
 * are computed by RelationshipGraphBuilder.
 */

import { FieldDefinition } from '../types/registry';

export const FIELD_REGISTRY: FieldDefinition[] = [
  // ============================================================================
  // DEMOGRAPHICS (9 fields)
  // ============================================================================
  {
    id: 'demographics.dateOfBirth',
    label: 'Date of Birth',
    path: 'demographics.dateOfBirth.value',
    type: 'DataPoint',
    dataType: 'string',
    category: 'Demographics',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'demographics.biologicalSex',
    label: 'Biological Sex',
    path: 'demographics.biologicalSex.value',
    type: 'DataPoint',
    dataType: 'BiologicalSex',
    category: 'Demographics',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'demographics.ethnicity',
    label: 'Ethnicity',
    path: 'demographics.ethnicity.value',
    type: 'DataPoint',
    dataType: 'Ethnicity',
    category: 'Demographics',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'demographics.educationLevel',
    label: 'Education Level',
    path: 'demographics.educationLevel.value',
    type: 'DataPoint',
    dataType: 'EducationLevel',
    category: 'Demographics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'demographics.country',
    label: 'Country',
    path: 'demographics.country.value',
    type: 'DataPoint',
    dataType: 'string',
    category: 'Demographics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'demographics.region',
    label: 'Region',
    path: 'demographics.region.value',
    type: 'DataPoint',
    dataType: 'string',
    category: 'Demographics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'demographics.urbanicity',
    label: 'Urbanicity',
    path: 'demographics.urbanicity.value',
    type: 'DataPoint',
    dataType: 'Urbanicity',
    category: 'Demographics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'demographics.zipCode',
    label: 'Zip Code',
    path: 'demographics.zipCode.value',
    type: 'DataPoint',
    dataType: 'string',
    category: 'Demographics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'demographics.genderIdentity',
    label: 'Gender Identity',
    path: 'demographics.genderIdentity.value',
    type: 'DataPoint',
    dataType: 'string',
    category: 'Demographics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // ============================================================================
  // BIOMETRICS (6 fields + 1 derived)
  // ============================================================================
  {
    id: 'biometrics.weight',
    label: 'Weight',
    path: 'biometrics.weight.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Biometrics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'biometrics.height',
    label: 'Height',
    path: 'biometrics.height.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Biometrics',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'biometrics.bloodPressure.systolic',
    label: 'Blood Pressure (Systolic)',
    path: 'biometrics.bloodPressure.mostRecent.value.systolic',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Biometrics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'biometrics.bloodPressure.diastolic',
    label: 'Blood Pressure (Diastolic)',
    path: 'biometrics.bloodPressure.mostRecent.value.diastolic',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Biometrics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'biometrics.heartRate',
    label: 'Heart Rate',
    path: 'biometrics.heartRate.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Biometrics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'biometrics.waistCircumference',
    label: 'Waist Circumference',
    path: 'biometrics.waistCircumference.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Biometrics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'biometrics.hipCircumference',
    label: 'Hip Circumference',
    path: 'biometrics.hipCircumference.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Biometrics',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Derived field
  {
    id: 'derived.bmi',
    label: 'BMI (Calculated)',
    path: 'derived.bmi',
    type: 'Derived',
    dataType: 'number',
    category: 'Biometrics',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
    derivedFrom: ['biometrics.weight', 'biometrics.height'],
  },

  // ============================================================================
  // LAB TESTS (30+ fields)
  // ============================================================================

  // Lipid Panel
  {
    id: 'labTests.lipidPanel.totalCholesterol',
    label: 'Total Cholesterol',
    path: 'labTests.lipidPanel.totalCholesterol.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.lipidPanel.ldlCholesterol',
    label: 'LDL Cholesterol',
    path: 'labTests.lipidPanel.ldlCholesterol.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.lipidPanel.hdlCholesterol',
    label: 'HDL Cholesterol',
    path: 'labTests.lipidPanel.hdlCholesterol.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.lipidPanel.triglycerides',
    label: 'Triglycerides',
    path: 'labTests.lipidPanel.triglycerides.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.lipidPanel.nonHdlCholesterol',
    label: 'Non-HDL Cholesterol',
    path: 'labTests.lipidPanel.nonHdlCholesterol.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.lipidPanel.apolipoproteinB',
    label: 'Apolipoprotein B',
    path: 'labTests.lipidPanel.apolipoproteinB.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.lipidPanel.lipoproteinA',
    label: 'Lipoprotein(a)',
    path: 'labTests.lipidPanel.lipoproteinA.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Metabolic Panel
  {
    id: 'labTests.metabolicPanel.glucose',
    label: 'Fasting Glucose',
    path: 'labTests.metabolicPanel.glucose.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.metabolicPanel.hba1c',
    label: 'HbA1c',
    path: 'labTests.metabolicPanel.hba1c.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.metabolicPanel.insulin',
    label: 'Insulin',
    path: 'labTests.metabolicPanel.insulin.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.metabolicPanel.creatinine',
    label: 'Creatinine',
    path: 'labTests.metabolicPanel.creatinine.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.metabolicPanel.eGFR',
    label: 'eGFR',
    path: 'labTests.metabolicPanel.eGFR.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.metabolicPanel.alt',
    label: 'ALT',
    path: 'labTests.metabolicPanel.alt.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.metabolicPanel.ast',
    label: 'AST',
    path: 'labTests.metabolicPanel.ast.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Complete Blood Count
  {
    id: 'labTests.cbc.wbc',
    label: 'White Blood Cell Count',
    path: 'labTests.cbc.wbc.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.cbc.rbc',
    label: 'Red Blood Cell Count',
    path: 'labTests.cbc.rbc.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.cbc.hemoglobin',
    label: 'Hemoglobin',
    path: 'labTests.cbc.hemoglobin.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.cbc.hematocrit',
    label: 'Hematocrit',
    path: 'labTests.cbc.hematocrit.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.cbc.platelets',
    label: 'Platelet Count',
    path: 'labTests.cbc.platelets.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Kidney Function
  {
    id: 'labTests.kidneyFunction.egfr',
    label: 'eGFR (Kidney)',
    path: 'labTests.kidneyFunction.egfr.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.kidneyFunction.serumCreatinine',
    label: 'Serum Creatinine',
    path: 'labTests.kidneyFunction.serumCreatinine.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.kidneyFunction.urineACR',
    label: 'Urine Albumin-to-Creatinine Ratio',
    path: 'labTests.kidneyFunction.urineACR.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Liver Function
  {
    id: 'labTests.liverFunction.ast',
    label: 'AST (Liver)',
    path: 'labTests.liverFunction.ast.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.liverFunction.alt',
    label: 'ALT (Liver)',
    path: 'labTests.liverFunction.alt.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.liverFunction.plateletCount',
    label: 'Platelet Count (Liver)',
    path: 'labTests.liverFunction.plateletCount.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.liverFunction.albumin',
    label: 'Albumin',
    path: 'labTests.liverFunction.albumin.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Other Lab Tests
  {
    id: 'labTests.psa',
    label: 'PSA (Prostate-Specific Antigen)',
    path: 'labTests.psa.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'labTests.vitaminD',
    label: 'Vitamin D',
    path: 'labTests.vitaminD.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'LabTests',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // ============================================================================
  // LIFESTYLE (40+ fields)
  // ============================================================================

  // Smoking
  {
    id: 'lifestyle.smoking.status',
    label: 'Smoking Status',
    path: 'lifestyle.smoking.status.value',
    type: 'DataPoint',
    dataType: 'SmokingStatus',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.smoking.packsPerDay',
    label: 'Packs Per Day',
    path: 'lifestyle.smoking.packsPerDay.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.smoking.packYears',
    label: 'Pack Years',
    path: 'lifestyle.smoking.packYears.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.smoking.quitDate',
    label: 'Quit Date',
    path: 'lifestyle.smoking.quitDate.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.smoking.yearsSinceQuitting',
    label: 'Years Since Quitting',
    path: 'lifestyle.smoking.yearsSinceQuitting.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Alcohol
  {
    id: 'lifestyle.alcohol.drinksPerWeek',
    label: 'Drinks Per Week',
    path: 'lifestyle.alcohol.drinksPerWeek.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.alcohol.bingeDrinking',
    label: 'Binge Drinking',
    path: 'lifestyle.alcohol.bingeDrinking.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.alcohol.pattern',
    label: 'Alcohol Consumption Pattern',
    path: 'lifestyle.alcohol.pattern.value',
    type: 'DataPoint',
    dataType: 'AlcoholPattern',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Exercise
  {
    id: 'lifestyle.exercise.moderateMinutesPerWeek',
    label: 'Moderate Exercise (min/week)',
    path: 'lifestyle.exercise.moderateMinutesPerWeek.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.exercise.vigorousMinutesPerWeek',
    label: 'Vigorous Exercise (min/week)',
    path: 'lifestyle.exercise.vigorousMinutesPerWeek.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.exercise.strengthTrainingDaysPerWeek',
    label: 'Strength Training (days/week)',
    path: 'lifestyle.exercise.strengthTrainingDaysPerWeek.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.exercise.sedentaryHoursPerDay',
    label: 'Sedentary Time (hours/day)',
    path: 'lifestyle.exercise.sedentaryHoursPerDay.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Sleep
  {
    id: 'lifestyle.sleep.averageHoursPerNight',
    label: 'Sleep Duration (hours/night)',
    path: 'lifestyle.sleep.averageHoursPerNight.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.sleep.sleepQuality',
    label: 'Sleep Quality (1-10)',
    path: 'lifestyle.sleep.sleepQuality.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Diet
  {
    id: 'lifestyle.diet.vegetableServingsPerDay',
    label: 'Vegetable Servings (per day)',
    path: 'lifestyle.diet.vegetableServingsPerDay.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.diet.fruitServingsPerDay',
    label: 'Fruit Servings (per day)',
    path: 'lifestyle.diet.fruitServingsPerDay.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.diet.processedMeatServingsPerWeek',
    label: 'Processed Meat (servings/week)',
    path: 'lifestyle.diet.processedMeatServingsPerWeek.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.diet.sugarSweetenedBeveragesPerWeek',
    label: 'Sugar-Sweetened Beverages (per week)',
    path: 'lifestyle.diet.sugarSweetenedBeveragesPerWeek.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.diet.pattern',
    label: 'Dietary Pattern',
    path: 'lifestyle.diet.pattern.value',
    type: 'DataPoint',
    dataType: 'DietPattern',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Driving Habits
  {
    id: 'lifestyle.drivingHabits.milesPerYear',
    label: 'Miles Driven Per Year',
    path: 'lifestyle.drivingHabits.milesPerYear.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.drivingHabits.seatBeltUse',
    label: 'Seatbelt Use',
    path: 'lifestyle.drivingHabits.seatBeltUse.value',
    type: 'DataPoint',
    dataType: 'SeatBeltFrequency',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.drivingHabits.trafficViolationsPast3Years',
    label: 'Traffic Violations (past 3 years)',
    path: 'lifestyle.drivingHabits.trafficViolationsPast3Years.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.drivingHabits.phoneUseWhileDriving',
    label: 'Phone Use While Driving',
    path: 'lifestyle.drivingHabits.phoneUseWhileDriving.value',
    type: 'DataPoint',
    dataType: 'PhoneUseFrequency',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.drivingHabits.drivingSetting',
    label: 'Driving Setting',
    path: 'lifestyle.drivingHabits.drivingSetting.value',
    type: 'DataPoint',
    dataType: 'DrivingSetting',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Other Lifestyle
  {
    id: 'lifestyle.occupationalExposures',
    label: 'Occupational Exposures',
    path: 'lifestyle.occupationalExposures.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.outdoorTime.minutesPerWeek',
    label: 'Outdoor Time (min/week)',
    path: 'lifestyle.outdoorTime.minutesPerWeek.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'lifestyle.outdoorTime.setting',
    label: 'Outdoor Setting',
    path: 'lifestyle.outdoorTime.setting.value',
    type: 'DataPoint',
    dataType: 'OutdoorSetting',
    category: 'Lifestyle',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // ============================================================================
  // MEDICAL HISTORY (50+ fields)
  // ============================================================================

  // Conditions (special - array)
  {
    id: 'medicalHistory.conditions',
    label: 'Medical Conditions',
    path: 'medicalHistory.conditions',
    type: 'Array',
    dataType: 'Condition[]',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Family History (special - array)
  {
    id: 'medicalHistory.familyHistory',
    label: 'Family History',
    path: 'medicalHistory.familyHistory',
    type: 'Array',
    dataType: 'FamilyCondition[]',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Screenings (special - array)
  {
    id: 'medicalHistory.screenings',
    label: 'Health Screenings',
    path: 'medicalHistory.screenings',
    type: 'Array',
    dataType: 'Screening[]',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Reproductive History
  {
    id: 'medicalHistory.reproductiveHistory.ageAtMenarche',
    label: 'Age at Menarche',
    path: 'medicalHistory.reproductiveHistory.ageAtMenarche.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.reproductiveHistory.ageAtFirstBirth',
    label: 'Age at First Birth',
    path: 'medicalHistory.reproductiveHistory.ageAtFirstBirth.value',
    type: 'DataPoint',
    dataType: 'string',
    category: 'MedicalHistory',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.reproductiveHistory.breastBiopsies',
    label: 'Number of Breast Biopsies',
    path: 'medicalHistory.reproductiveHistory.breastBiopsies.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.reproductiveHistory.atypicalHyperplasia',
    label: 'Atypical Hyperplasia',
    path: 'medicalHistory.reproductiveHistory.atypicalHyperplasia.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Urinary History
  {
    id: 'medicalHistory.urinaryHistory.priorNegativeBiopsy',
    label: 'Prior Negative Biopsy',
    path: 'medicalHistory.urinaryHistory.priorNegativeBiopsy.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Respiratory History
  {
    id: 'medicalHistory.respiratoryHistory.fev1Percent',
    label: 'FEV1 Percent',
    path: 'medicalHistory.respiratoryHistory.fev1Percent.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.respiratoryHistory.dyspneaSeverity',
    label: 'Dyspnea Severity',
    path: 'medicalHistory.respiratoryHistory.dyspneaSeverity.value',
    type: 'DataPoint',
    dataType: 'DyspneaSeverity',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.respiratoryHistory.exacerbationsPerYear',
    label: 'Exacerbations Per Year',
    path: 'medicalHistory.respiratoryHistory.exacerbationsPerYear.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Genetic Factors
  {
    id: 'medicalHistory.geneticFactors.apoeE4Status',
    label: 'APOE ε4 Status',
    path: 'medicalHistory.geneticFactors.apoeE4Status.value',
    type: 'DataPoint',
    dataType: 'ApoeE4Status',
    category: 'MedicalHistory',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Fall History
  {
    id: 'medicalHistory.fallHistory.fallsPastYear',
    label: 'Falls in Past Year',
    path: 'medicalHistory.fallHistory.fallsPastYear.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.fallHistory.fallWithInjury',
    label: 'Fall with Injury',
    path: 'medicalHistory.fallHistory.fallWithInjury.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.fallHistory.balanceProblems',
    label: 'Balance Problems',
    path: 'medicalHistory.fallHistory.balanceProblems.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.fallHistory.dizzinessWhenStanding',
    label: 'Dizziness When Standing',
    path: 'medicalHistory.fallHistory.dizzinessWhenStanding.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Medications
  {
    id: 'medicalHistory.medications.totalMedicationCount',
    label: 'Total Medication Count',
    path: 'medicalHistory.medications.totalMedicationCount.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.medications.takesBloodPressureMeds',
    label: 'Takes Blood Pressure Medication',
    path: 'medicalHistory.medications.takesBloodPressureMeds.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.medications.prescribedBenzodiazepines',
    label: 'Prescribed Benzodiazepines',
    path: 'medicalHistory.medications.prescribedBenzodiazepines.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.medications.statin',
    label: 'Takes Statin',
    path: 'medicalHistory.medications.statin.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Vaccinations
  {
    id: 'medicalHistory.vaccinations.fluVaccineCurrentYear',
    label: 'Flu Vaccine (Current Year)',
    path: 'medicalHistory.vaccinations.fluVaccineCurrentYear.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.vaccinations.pneumococcalVaccine',
    label: 'Pneumococcal Vaccine',
    path: 'medicalHistory.vaccinations.pneumococcalVaccine.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.vaccinations.lastFluVaccine',
    label: 'Last Flu Vaccine Date',
    path: 'medicalHistory.vaccinations.lastFluVaccine.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.vaccinations.lastPneumococcalVaccine',
    label: 'Last Pneumococcal Vaccine Date',
    path: 'medicalHistory.vaccinations.lastPneumococcalVaccine.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Mental Health
  {
    id: 'medicalHistory.mentalHealth.depressionDiagnosis',
    label: 'Depression Diagnosis',
    path: 'medicalHistory.mentalHealth.depressionDiagnosis.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.mentalHealth.anxietyDiagnosis',
    label: 'Anxiety Diagnosis',
    path: 'medicalHistory.mentalHealth.anxietyDiagnosis.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.mentalHealth.currentlyInTreatment',
    label: 'Currently in Mental Health Treatment',
    path: 'medicalHistory.mentalHealth.currentlyInTreatment.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Substance Use
  {
    id: 'medicalHistory.substanceUse.prescribedOpioids',
    label: 'Prescribed Opioids',
    path: 'medicalHistory.substanceUse.prescribedOpioids.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.substanceUse.opioidDailyDose',
    label: 'Opioid Daily Dose (MME)',
    path: 'medicalHistory.substanceUse.opioidDailyDose.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.substanceUse.illicitDrugUse',
    label: 'Illicit Drug Use',
    path: 'medicalHistory.substanceUse.illicitDrugUse.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.substanceUse.substanceAbuseHistory',
    label: 'Substance Abuse History',
    path: 'medicalHistory.substanceUse.substanceAbuseHistory.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.substanceUse.priorOverdose',
    label: 'Prior Overdose',
    path: 'medicalHistory.substanceUse.priorOverdose.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Gastrointestinal History
  {
    id: 'medicalHistory.gastrointestinalHistory.gerdDiagnosis',
    label: 'GERD Diagnosis',
    path: 'medicalHistory.gastrointestinalHistory.gerdDiagnosis.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.gastrointestinalHistory.barretsEsophagus',
    label: "Barrett's Esophagus",
    path: 'medicalHistory.gastrointestinalHistory.barretsEsophagus.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Hepatitis History
  {
    id: 'medicalHistory.hepatitisHistory.hepatitisB',
    label: 'Hepatitis B',
    path: 'medicalHistory.hepatitisHistory.hepatitisB.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.hepatitisHistory.hepatitisC',
    label: 'Hepatitis C',
    path: 'medicalHistory.hepatitisHistory.hepatitisC.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Other Medical History
  {
    id: 'medicalHistory.immuneStatus',
    label: 'Immune Status',
    path: 'medicalHistory.immuneStatus.value',
    type: 'DataPoint',
    dataType: 'ImmuneStatus',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.suicideAttempts',
    label: 'Suicide Attempts',
    path: 'medicalHistory.suicideAttempts.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.sunExposure.sunburns',
    label: 'Lifetime Sunburns',
    path: 'medicalHistory.sunExposure.sunburns.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.sunExposure.sunscreenUse',
    label: 'Sunscreen Use',
    path: 'medicalHistory.sunExposure.sunscreenUse.value',
    type: 'DataPoint',
    dataType: 'SunscreenUse',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.cacScore',
    label: 'Coronary Artery Calcium (CAC) Score',
    path: 'medicalHistory.cacScore.value',
    type: 'DataPoint',
    dataType: 'CACScore',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.sleepApnea.diagnosis',
    label: 'Sleep Apnea Diagnosis',
    path: 'medicalHistory.sleepApnea.diagnosis.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.sleepApnea.onTreatment',
    label: 'Sleep Apnea on Treatment',
    path: 'medicalHistory.sleepApnea.onTreatment.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.sleepApnea.severity',
    label: 'Sleep Apnea Severity',
    path: 'medicalHistory.sleepApnea.severity.value',
    type: 'DataPoint',
    dataType: 'SleepApneaSeverity',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.hearingLoss.treated',
    label: 'Hearing Loss Treatment Status',
    path: 'medicalHistory.hearingLoss.treated.value',
    type: 'DataPoint',
    dataType: 'HearingLossTreated',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'medicalHistory.hearingLoss.severity',
    label: 'Hearing Loss Severity',
    path: 'medicalHistory.hearingLoss.severity.value',
    type: 'DataPoint',
    dataType: 'HearingLossSeverity',
    category: 'MedicalHistory',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // ============================================================================
  // SOCIAL (20+ fields)
  // ============================================================================

  // Pet Ownership
  {
    id: 'social.petOwnership.ownsDog',
    label: 'Owns Dog',
    path: 'social.petOwnership.ownsDog.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.petOwnership.ownsCat',
    label: 'Owns Cat',
    path: 'social.petOwnership.ownsCat.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.petOwnership.ownershipDurationYears',
    label: 'Pet Ownership Duration (years)',
    path: 'social.petOwnership.ownershipDurationYears.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.petOwnership.otherPets',
    label: 'Other Pets',
    path: 'social.petOwnership.otherPets.value',
    type: 'DataPoint',
    dataType: 'string[]',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Social Connections
  {
    id: 'social.connections.strength',
    label: 'Social Connection Strength',
    path: 'social.connections.strength.value',
    type: 'DataPoint',
    dataType: 'SocialConnectionStrength',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.connections.closeRelationshipsCount',
    label: 'Close Relationships Count',
    path: 'social.connections.closeRelationshipsCount.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.connections.socialActivityFrequency',
    label: 'Social Activity Frequency',
    path: 'social.connections.socialActivityFrequency.value',
    type: 'DataPoint',
    dataType: 'SocialActivityFrequency',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.connections.livesAlone',
    label: 'Lives Alone',
    path: 'social.connections.livesAlone.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.connections.maritalStatus',
    label: 'Marital Status',
    path: 'social.connections.maritalStatus.value',
    type: 'DataPoint',
    dataType: 'MaritalStatus',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Religious Attendance
  {
    id: 'social.religiousAttendance',
    label: 'Religious Service Attendance',
    path: 'social.religiousAttendance.value',
    type: 'DataPoint',
    dataType: 'ReligiousAttendanceFrequency',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Volunteering
  {
    id: 'social.volunteering.active',
    label: 'Currently Volunteers',
    path: 'social.volunteering.active.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.volunteering.hoursPerMonth',
    label: 'Volunteering Hours Per Month',
    path: 'social.volunteering.hoursPerMonth.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.volunteering.organizationsCount',
    label: 'Number of Volunteer Organizations',
    path: 'social.volunteering.organizationsCount.value',
    type: 'DataPoint',
    dataType: 'number',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.volunteering.type',
    label: 'Volunteering Type',
    path: 'social.volunteering.type.value',
    type: 'DataPoint',
    dataType: 'VolunteeringType[]',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Hobbies - Creative
  {
    id: 'social.hobbies.creative.engaged',
    label: 'Engaged in Creative Hobbies',
    path: 'social.hobbies.creative.engaged.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.hobbies.creative.types',
    label: 'Creative Hobby Types',
    path: 'social.hobbies.creative.types.value',
    type: 'DataPoint',
    dataType: 'CreativeHobbyType[]',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.hobbies.creative.hoursPerWeek',
    label: 'Creative Hobby Hours Per Week',
    path: 'social.hobbies.creative.hoursPerWeek.mostRecent.value',
    type: 'TimeSeries',
    dataType: 'number',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Hobbies - Physical
  {
    id: 'social.hobbies.physical.engaged',
    label: 'Engaged in Physical Hobbies',
    path: 'social.hobbies.physical.engaged.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.hobbies.physical.types',
    label: 'Physical Hobby Types',
    path: 'social.hobbies.physical.types.value',
    type: 'DataPoint',
    dataType: 'PhysicalHobbyType[]',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Hobbies - Social
  {
    id: 'social.hobbies.social.engaged',
    label: 'Engaged in Social Hobbies',
    path: 'social.hobbies.social.engaged.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.hobbies.social.types',
    label: 'Social Hobby Types',
    path: 'social.hobbies.social.types.value',
    type: 'DataPoint',
    dataType: 'SocialHobbyType[]',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Hobbies - Intellectual
  {
    id: 'social.hobbies.intellectual.engaged',
    label: 'Engaged in Intellectual Hobbies',
    path: 'social.hobbies.intellectual.engaged.value',
    type: 'DataPoint',
    dataType: 'boolean',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },
  {
    id: 'social.hobbies.intellectual.types',
    label: 'Intellectual Hobby Types',
    path: 'social.hobbies.intellectual.types.value',
    type: 'DataPoint',
    dataType: 'IntellectualHobbyType[]',
    category: 'Social',
    modifiable: true,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
  },

  // Derived Age Field (calculated from dateOfBirth)
  {
    id: 'derived.age',
    label: 'Age (Calculated)',
    path: 'derived.age',
    type: 'Derived',
    dataType: 'number',
    category: 'Demographics',
    modifiable: false,
    usedByRiskFactors: [],
    usedByDiseases: [],
    mappedFromQuestions: [],
    derivedFrom: ['demographics.dateOfBirth'],
  },
];
